apiVersion: api.cerbos.dev/v1
resourcePolicy:
  version: "default"
  resource: allowed_link
  rules:
    - actions: ["view"]
      roles:
        - transaction-submitter
        - transaction-admin
        - transaction-config-admin
      effect: EFFECT_ALLOW

    - actions: ["create"]
      roles:
        - transaction-config-admin
      effect: EFFECT_ALLOW
