apiVersion: api.cerbos.dev/v1
resourcePolicy:
  version: "default"
  resource: form_configuration
  rules:
    - actions: ["view"]
      roles:
        - transaction-submitter
        - transaction-admin
        - transaction-config-admin
      effect: EFFECT_ALLOW

    - actions: ["create", "update", "publish", "unpublish"]
      roles:
        - transaction-config-admin
      effect: EFFECT_ALLOW