apiVersion: api.cerbos.dev/v1
resourcePolicy:
  version: "default"
  resource: transaction_link_type
  rules:
    - actions: ["view"]
      roles:
        - transaction-submitter
        - transaction-admin
        - transaction-config-admin
      effect: EFFECT_ALLOW

    - actions: ["create", "delete"]
      roles:
        - transaction-config-admin
      effect: EFFECT_ALLOW
